<style>
.tablecustom input, .tablecustom select{
	width:200px;
}
</style>
<div class="content-header">
    <h3 class="icon-head head-sales-order-invoice"><?php echo $this->getHeaderText()?></h3>    
	<p class="form-buttons">
	<button style="" onclick="setLocation('<?php echo $this->getBackUrl()?>')" class="scalable back" type="button" title="Back">
		<span><span><span>Back</span></span></span>
	</button>
	<button style="" onclick="setLocation(window.location.href)" class="scalable " type="button" title="Reset">
		<span><span><span>Reset</span></span></span>
	</button>
	</p>
</div>
<?php
$presets = Mage::getModel('linksynceparcel/preset')
				->getCollection()
				->addFilter('status', array('eq' => 1));
?>
<?php  $_order = $this->getOrder() ?>
<?php  $consignment = $this->getConsignment(); ?>
<?php  $article = $this->getArticle() ?>
<?php
	$use_order_total_weight = (int)Mage::getStoreConfig('carriers/linksynceparcel/use_order_total_weight');
	$use_article_dimensions = (int)Mage::getStoreConfig('carriers/linksynceparcel/use_article_dimensions');
	if($use_order_total_weight == 1)
	{
		$weight = Mage::helper('linksynceparcel')->getOrderWeight($_order);
		if($weight == 0)
		{
			$default_article_weight = Mage::getStoreConfig('carriers/linksynceparcel/default_article_weight');
			if($default_article_weight)
			{
				$weight = $default_article_weight;
			}
		}
		$weightPerArticle = Mage::helper('linksynceparcel')->getAllowedWeightPerArticle();
	}
	
	$selected = false;
	$selectedWeight = 0;
	if($weight <= $weightPerArticle)
	{
		 $upCheck = $weightPerArticle - $weight;
		if(Mage::helper('linksynceparcel')->presetMatch($presets,$weight))
		{
			$selectedWeight = $weight;
		}
		else
		{
			for($i=.01;$i<=$upCheck;$i = $i + 0.01)
			{
				$newUpWeight = $weight + $i;
				if(Mage::helper('linksynceparcel')->presetMatch($presets,$newUpWeight))
				{
					$selectedWeight = ''.$newUpWeight.'';
					break;
				}
			}
		}
	}
?>
<form name="edit_form" id="edit_form" method="post" action="<?php echo $this->getSaveUrl() ?>">
    <?php echo $this->getBlockHtml('formkey')?>
	<input id="order_id" type="hidden" name="order_id" value="<?php echo $this->getOrder()->getId()?>" />
	<input id="number_of_articles" name="number_of_articles" size="4" value="1" type="hidden"/>
    
     <?php if($use_article_dimensions == 1): ?>
    <div class="box" id="presets">
       <!-- Articles&nbsp;&nbsp; <input id="number_of_articles" name="number_of_articles" size="4" value="1" class="validate-number" style="text-align:center; padding:3px" />&nbsp;&nbsp;&nbsp;&nbsp;-->
       
      
        Article Type&nbsp;&nbsp; 
        <select id="articles_type" name="articles_type" class="required-entry2" style="padding:3px" >
            <?php
           
            foreach($presets as $preset)
            {
                ?>
                <option value="<?php echo $preset->getName().'<=>'.$preset->getWeight().'<=>'.$preset->getHeight().'<=>'.$preset->getWidth().'<=>'.$preset->getLength()?>"
					<?php 
                    if($preset->getWeight() == $selectedWeight && !$selected)
                    {
                        echo 'selected="selected"'; 
                        $selected = true;
                    }
                    ?>
                >
                    <?php echo $preset->getName(). ' ('.$preset->getWeight().'kg - '.$preset->getHeight().'x'.$preset->getWidth().'x'.$preset->getLength().')'?>
                </option>
                <?php
            }
            ?>
            <option value="Custom" <?php echo ($weight > $weightPerArticle) ? 'selected="selected"' : ''?>>Custom</option>
        </select>
        &nbsp;&nbsp;&nbsp;&nbsp;
        
        <button style="" onclick="return submitForm2()" class="create-consignment1 scalable save submit-button <?php if($this->getOrder()->getStatus() == 'complete'){ echo 'disabled';}?>" type="button" title="Submit" <?php if($this->getOrder()->getStatus() == 'complete'){ echo 'disabled="disabled"';}?>><span><span><span>Add Article</span></span></span></button>
		
    </div>
    <?php else: ?>
		<input type="hidden" id="articles_type" name="articles_type" value="Custom"/>
    <?php endif; ?>
    
	<div class="box custom_articles_template" style="display:none">
        <h3>Article</h3>
        <span class="field-row1">
            <label class="normal" for="article_description">
                <?php echo Mage::helper('sales')->__('Description:') ?><span class="required">*</span>
            </label>
            <input id="article_description" name="article[description]" class="required-entry" value="Article"/>
        </span>
        <span class="field-row1">
            <label class="normal" for="article_weight">
                <?php echo Mage::helper('sales')->__('Weight (Kgs):') ?><span class="required">*</span>
            </label>
            <?php if($use_order_total_weight == 1): ?>
            <input size="10" style="text-align:center" id="article_weight" name="article[weight]" class="required-entry positive-number maximum-value" label="Weight" value="<?php echo ($weight > $weightPerArticle) ? $weightPerArticle : $weight?>"/>
            <?php else: ?>
                <input size="10" style="text-align:center" id="article_weight" name="article[weight]" class="required-entry positive-number" label="Weight" value="<?php echo Mage::getStoreConfig('carriers/linksynceparcel/default_article_weight')?>"/>
            <?php endif; ?>
        </span>
        <?php if($use_article_dimensions == 1): ?>
        <span class="field-row1">
            <label class="normal" for="article_height">
                <?php echo Mage::helper('sales')->__('Height (cm):') ?>
            </label>
            <input size="10" style="text-align:center" id="article_height" class="positive-number" label="Height" name="article[height]"  value="<?php echo Mage::getStoreConfig('carriers/linksynceparcel/default_article_height')?>"/>
        </span>
        <span class="field-row1">
            <label class="normal" for="article_width">
                <?php echo Mage::helper('sales')->__('Width (cm):') ?>
            </label>
            <input size="10" style="text-align:center" id="article_width" class="positive-number" label="Width" name="article[width]" value="<?php echo Mage::getStoreConfig('carriers/linksynceparcel/default_article_width')?>"/>
        </span>
        <span class="field-row1">
            <label class="normal" for="article_length">
                <?php echo Mage::helper('sales')->__('Length (cm):') ?>
            </label>
            <input size="10" style="text-align:center" id="article_length" class="positive-number" label="Length" name="article[length]" value="<?php echo Mage::getStoreConfig('carriers/linksynceparcel/default_article_length')?>"/>
        </span>
         <?php else: ?>
            <input type="hidden" name="article[height]" value="0"/>
            <input type="hidden" name="article[width]" value="0"/>
            <input type="hidden" name="article[length]" value="0"/>
        <?php endif; ?>
    </div>
        
    <div id="custom_articles" style="display:none">
        <div id="custom_articles_container">
        </div>
        
        <button style="" onclick="backToPreset()" class="scalable back backToPreset" type="button" title="Back">
            <span><span><span>Back to Preset</span></span></span>
        </button>
        &nbsp;&nbsp;
        <button style="" onclick="return submitForm()" class="scalable save submit-button <?php if($this->getOrder()->getStatus() == 'complete'){ echo 'disabled';}?>" type="button" title="Submit" <?php if($this->getOrder()->getStatus() == 'complete'){ echo 'disabled="disabled"';}?>><span><span><span>Add Article</span></span></span></button>
    </div>
    
     <div>
        <br />
        <a href="javascript:void(0)" class="edit-consignments-defaults" style="text-decoration:none"><span style="font-size:13px; color:#F60">Edit Consignment Fields</span></a>
        <br />
        <br />
     </div>
        
        <div class="box consignment-fields" style="display:none">
			<h3>Consignment Fields</h3>
			<table width="100%" border="0" cellspacing="6" cellpadding="6" class="tablecustom">
			  <tr>
				<td width="20%"><?php echo Mage::helper('sales')->__('Partial Delivery allowed?') ?></td>
				<td>
                <?php if(Mage::helper('linksynceparcel')->isDisablePartialDeliveryMethod($_order->getId())): ?>
                <select id="partial_delivery_allowed" name="partial_delivery_allowed" disabled="disabled">
					<option value="0">No</option>
				</select>
                <?php else: ?>
                <select id="partial_delivery_allowed" name="partial_delivery_allowed" >
					<option value="1" <?php echo (($consignment['partial_delivery_allowed'])==1?'selected':'')?>>Yes</option>
					<option value="0" <?php echo (($consignment['partial_delivery_allowed'])!=1?'selected':'')?>>No</option>
				</select>	
                 <?php endif; ?>
                </td>
			  </tr>
			  
			  <?php if(Mage::helper('linksynceparcel')->isCashToCollect($_order->getId())): ?>
			  <tr>
				<td><?php echo Mage::helper('sales')->__('Cash to collect') ?></td>
				<td><input id="cash_to_collect" name="cash_to_collect" value="<?php echo $consignment['cash_to_collect']?>"/></td>
			  </tr>
			  <?php endif; ?>
			  
			  <tr>
				<td><?php echo Mage::helper('sales')->__('Delivery signature required?') ?></td>
				<td><select id="delivery_signature_allowed" name="delivery_signature_allowed">
					<option value="1" <?php echo ($consignment['delivery_signature_allowed']==1?'selected':'')?>>Yes</option>
					<option value="0" <?php echo ($consignment['delivery_signature_allowed']!=1?'selected':'')?>>No</option>
				</select></td>
			  </tr>
			  <tr>
				<td><?php echo Mage::helper('sales')->__('Transit cover required?') ?></td>
				<td><select id="transit_cover_required" name="transit_cover_required">
					<option value="1" <?php echo (Mage::getStoreConfig('carriers/linksynceparcel/insurance')==1?'selected':'')?>>Yes</option>
					<option value="0" <?php echo (Mage::getStoreConfig('carriers/linksynceparcel/insurance')!=1?'selected':'')?>>No</option>
				</select></td>
			  </tr>
			  <tr>
				<td><?php echo Mage::helper('sales')->__('Transit cover Amount') ?></td>
				<td><input id="transit_cover_amount" class="positive-number" label="Transit cover amount" name="transit_cover_amount" value="<?php echo Mage::getStoreConfig('carriers/linksynceparcel/default_insurance_value')?>" /></td>
			  </tr>
			  <tr>
				<td><?php echo Mage::helper('sales')->__('Shipment contains dangerous goods?') ?></td>
				<td><select id="contains_dangerous_goods" name="contains_dangerous_goods">
					<option value="1" <?php echo ($consignment['contains_dangerous_goods']==1?'selected':'')?>>Yes</option>
					<option value="0" <?php echo ($consignment['contains_dangerous_goods']!=1?'selected':'')?>>No</option>
				</select></td>
			  </tr>
			  <tr>
				<td><?php echo Mage::helper('sales')->__('Print return labels?') ?></td>
				<td><select id="print_return_labels" name="print_return_labels">
					<option value="1" <?php echo ($consignment['print_return_labels']==1?'selected':'')?>>Yes</option>
					<option value="0" <?php echo ($consignment['print_return_labels']!=1?'selected':'')?>>No</option>
				</select></td>
			  </tr>
              <tr>
				<td><?php echo Mage::helper('sales')->__('Australia Post email notification?') ?></td>
				<td><select id="email_notification" name="email_notification">
					<option value="1" <?php echo ($consignment['email_notification']==1?'selected':'')?>>Yes</option>
					<option value="0" <?php echo ($consignment['email_notification']!=1?'selected':'')?>>No</option>
				</select></td>
			  </tr>
               <tr>
				<td><?php echo Mage::helper('sales')->__('Notify Customers?') ?></td>
				<td><select id="notify_customers" name="notify_customers">
					<option value="1" <?php echo ($consignment['notify_customers']==1?'selected':'')?>>Yes</option>
					<option value="0" <?php echo ($consignment['notify_customers']!=1?'selected':'')?>>No</option>
				</select></td>
			  </tr>
			</table>
			
	</div>
    <div class="clear"></div>
	
	<!--<button style="" onclick="return submitForm()" class="scalable save submit-button" type="button" title="Submit"><span><span><span>Add Article</span></span></span></button>-->
    
</form>
<script>
<?php if($use_order_total_weight == 1): ?>
var weightPerArticle = '<?php echo $weightPerArticle?>';
<?php endif; ?>
$jEparcel = jQuery.noConflict();
$jEparcel(document).ready(function(){
	$jEparcel('.edit-consignments-defaults').click(function(){
		$jEparcel('.consignment-fields').slideToggle();
	});
	
	$jEparcel('#number_of_articles').blur(function(){
		var value = $jEparcel.trim($jEparcel(this).val());
		if(value.length == 0)
		{
			alert('Articles should not be empty');
			$jEparcel(this).val(1);
		}
		if(isNaN(value))
		{
			alert('Articles should be a number');
			$jEparcel(this).val(1);
		}
		
		value = parseInt(value);
		if(value < 0)
		{
			alert('Articles should be a postive number');
			$jEparcel(this).val(1);
		}
	});
	
	if($jEparcel('#articles_type').val() == 'Custom')
	{
		$jEparcel('.create-consignment1').hide(); 
		$jEparcel('.backToPreset').hide(); 
		$jEparcel('#custom_articles').show(); 
			
		var number_of_articles = $jEparcel('#number_of_articles').val();
		for(var i=1; i<=number_of_articles; i++)
		{
			var box = $jEparcel('.custom_articles_template').clone(); 
			box.removeClass('custom_articles_template');
			box.find('h3').html(box.find('h3').html()+' '+i);
			box.find('#article_description').val(box.find('#article_description').val()+' '+i);
			box.show();
			$jEparcel('#custom_articles_container').append(box);
		}
	}
	
	$jEparcel('#articles_type').change(function(){
		$jEparcel('.backToPreset').hide(); 
		if($jEparcel(this).val() == 'Custom')
		{
			$jEparcel('.create-consignment1').hide();
			$jEparcel('#presets').show(); 
			$jEparcel('#custom_articles').show(); 
			
			var number_of_articles = $jEparcel('#number_of_articles').val();
			for(var i=1; i<=number_of_articles; i++)
			{
				var box = $jEparcel('.custom_articles_template').clone(); 
				box.removeClass('custom_articles_template');
				box.find('h3').html(box.find('h3').html()+' '+i);
				box.find('#article_description').val(box.find('#article_description').val()+' '+i);
				box.show();
				$jEparcel('#custom_articles_container').append(box);
			}
		}
		else
		{
			$jEparcel('#presets').show();
			$jEparcel('#custom_articles').hide(); 
			$jEparcel('#custom_articles_container').html(''); 
			$jEparcel('.create-consignment1').show();
		}
	});
});

function backToPreset()
{
	$jEparcel('#presets').show();
	$jEparcel('#custom_articles').hide(); 
	$jEparcel('#custom_articles_container').html(''); 
	$jEparcel('#articles_type').val($jEparcel('#articles_type > option:first').attr('value'));
}

function submitForm()
{
	var valid = true;
	
	var value = $jEparcel.trim($jEparcel('#articles_type').val());
	if(value.length == 0 && valid)
	{
		valid = false;
		alert('Please select article type');
		return false;
	}
	
	$jEparcel('#custom_articles_container .required-entry').each(function(){
		var value = $jEparcel.trim($jEparcel(this).val());
		if(value.length == 0 && valid)
		{
			valid = false;
		}
	});
	if(!valid)
	{
		alert('Please enter all the mandatory fields');
		return false;
	}
	$jEparcel('.positive-number').each(function(){
		var value = $jEparcel.trim($jEparcel(this).val());
		var label = $jEparcel(this).attr('label');
		if(isNaN(value))
		{
			alert(label +' should be a number');
			valid = false;
		}
		
		value = parseInt(value);
		if(value < 0)
		{
			alert(label +' should be a postive number');
			valid = false;
		}
		
	});
	if(!valid)
	{
		return false;
	}
	<?php if($use_order_total_weight == 1): ?>
	$jEparcel('.maximum-value').each(function(){
		var value = $jEparcel.trim($jEparcel(this).val());
		var label = $jEparcel(this).attr('label');
		value = parseFloat(value);
		if(value > weightPerArticle)
		{
			alert('Allowed weight per article is '+ weightPerArticle);
			valid = false;
		}
		
	});
	if(!valid)
	{
		return false;
	}
	else
	{
		$('edit_form').submit();
	}
	<?php else: ?>
		$('edit_form').submit();
	<?php endif; ?>
}
function submitForm2()
{
	$('edit_form').submit();
}
</script>
